
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    command:
      - --storageEngine=wiredTiger
      - --replSet=rs0
      - --quiet
    volumes:
      - ./mongo/init-rs.js:/docker-entrypoint-initdb.d/init-rs.js
    deploy:
      resources:
        limits:
          memory: 2G        # Hard limit
        reservations:
          memory: 1G        # Soft limit (guaranteed)


  meteor:
    build: ./meteor
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017/benchmark?replicaSet=rs0&directConnection=true
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs0&directConnection=true
      - PORT=3000
      - METEOR_ALLOW_SUPERUSER=true
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'       # Also limit CPU cores
        reservations:
          memory: 512M

  tester:
    build: ./tester
    depends_on:
      meteor:
        condition: service_healthy
    environment:
      - MONGO_URL=mongodb://mongo:27017/benchmark?replicaSet=rs0&directConnection=true
      - METEOR_URL=ws://meteor:3000/websocket
      - CUSTOMERS=500
      - DURATION=50
      - INIT_TIME=10
      - DENSITY=100
      - DOCUMENTS=10000
    volumes:
      - ./tester/main.js:/app/main.js
      - ./tester/log:/app/log
    command: ["node", "main.js"]

